# Generated by Django 6.0.4 on 2026-04-14 10:50

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20260412_1452'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
